name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for MIPS
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: mips
            gomips: softfloat
            suffix: mips-softfloat
          - goos: linux
            goarch: mips
            gomips: hardfloat
            suffix: mips-hardfloat
          - goos: linux
            goarch: mipsle
            gomips: softfloat
            suffix: mipsle-softfloat
          - goos: linux
            goarch: mipsle
            gomips: hardfloat
            suffix: mipsle-hardfloat

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOMIPS: ${{ matrix.gomips }}
      run: |
        go build -ldflags="-s -w -X main.version=${{ github.sha }}" \
          -o xray-telegram-manager-${{ matrix.suffix }} .

    - name: Compress binary with UPX
      run: |
        # Install UPX for binary compression
        wget -q https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz
        tar -xf upx-4.2.1-amd64_linux.tar.xz
        sudo mv upx-4.2.1-amd64_linux/upx /usr/local/bin/
        
        # Compress the binary (skip if compression fails)
        upx --best --lzma xray-telegram-manager-${{ matrix.suffix }} || echo "UPX compression failed, continuing with uncompressed binary"

    - name: Generate checksum
      run: |
        sha256sum xray-telegram-manager-${{ matrix.suffix }} > xray-telegram-manager-${{ matrix.suffix }}.sha256

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xray-telegram-manager-${{ matrix.suffix }}
        path: |
          xray-telegram-manager-${{ matrix.suffix }}
          xray-telegram-manager-${{ matrix.suffix }}.sha256
        retention-days: 30

  build-info:
    name: Build Information
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Display build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "Built binaries for the following MIPS variants:" >> $GITHUB_STEP_SUMMARY
        echo "- MIPS softfloat" >> $GITHUB_STEP_SUMMARY
        echo "- MIPS hardfloat" >> $GITHUB_STEP_SUMMARY
        echo "- MIPSLE softfloat" >> $GITHUB_STEP_SUMMARY
        echo "- MIPSLE hardfloat" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All binaries have been compressed with UPX and checksums generated." >> $GITHUB_STEP_SUMMARY
        echo "Artifacts are available for download for 30 days." >> $GITHUB_STEP_SUMMARY